version: "3.9"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    command: bash -c "bundle exec rails db:migrate db:seed && bundle exec rails server -b 0.0.0.0 -p 3001"
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: blog_development
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy

  web:
      web:
      build: ./web
      ports:
      - "3000:3000"
      environment:
      NEXT_PUBLIC_GRAPHQL_URL: http://localhost:3001/graphql  # <-- change api to localhost
      depends_on:
      - api

volumes:
  mysql_data:
