default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <%= ENV.fetch("DB_USER", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  ssl_mode: disabled

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "blog_development") %>